@echo off
echo Starting Option Scanner Pro Web UI...
cd /d "%~dp0"
echo Installing Dependencies...
pip install fastapi uvicorn jinja2 aiofiles
echo Launching Server...
python -m uvicorn web_ui.web_app:app --host 127.0.0.1 --port 8000 --log-level info
pause
